name: vitraya-ramunong
description: Keep your forks at sight

inputs:
  owner:
    description: repo owner
    required: true
  repo:
    description: repository name
    required: true
  token:
    description: Github token
    required: true

runs:
  using: docker
  image: Dockerfile