name: show_forks

on:
  push:
    branches:
      - dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - run: |
          forks="$(gh api graphql -F owner=$OWNER -F name=$REPO -f query='
            query($name: String!, $owner: String!) {
              repository(owner: $owner, name: $name){
                forkCount
                forks(first: 10, orderBy: {field: NAME, direction: DESC}) {
                    totalCount
                    nodes {
                      owner {
                        id
                      }
                      name
                      nameWithOwner
                    }
                  }
                }
              }
            }
          ' --jq '.data.repository.forks') | jq -rc"
          echo $forks
          echo 'REPO_FORKS='$forks >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
      - run: |
          echo $REPO_FORKS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        